### ISSUE TITLE
🐛 BUG: Auto commenting using Ctrl + / key doesn't work inside JSX {} operator

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/astro-language-tools#102]
### Describe the Bug

Auto commenting using `Ctrl + /` key doesn't work inside JSX {} operator. The code gets commented using HTML comments instead of JS comments.

### Steps to Reproduce

Auto commenting using the `Ctrl + /` key should work inside JSX {} operator

**Comment by jasikpark** [comment]
So you're imagining selecting the code inside a handlebar just comments out that js code rather than the outer {} context?

```astro
{// doStuff()
  // .thenDoMoreStuff}
```

rather than

```astro
<!-- {doStuff()
  .thenDoMoreStuff} -->
```

**Comment by RafidMuhymin** [comment]
@jasikpark Yeah, the code is commented using HTML comments but it should be commented using JS comments
