### ISSUE TITLE
🐛 BUG: Template literal attributes aren't highlighted properly

### ISSUE THREAD

**Issue by natemoo-re** [withastro/astro-language-tools#111]
### Describe the Bug

Astro v0.21 introduce template literal attributes with the following syntax:

```
<div atrr=`some ${value}`>
```

These currently don't have any syntax highlighting.

### Steps to Reproduce

1. Paste the snippet above into an `.astro` file

**Comment by jonathantneal** [comment]
Syntax highlighting was added in https://github.com/withastro/astro-language-tools/pull/115
