### ISSUE TITLE
🐛 BUG: properties in PostCSS not highlighted properly

### ISSUE THREAD

**Issue by ptrxyz** [withastro/astro-language-tools#120]
### Describe the Bug

I am using VSCode (latest, 1.62.3, on Linux) and the Astro VSCode extension (latest, 0.8.2). My Astro file contains a PostCSS-style block, yet the properties are not highlighted properly.

Compare the two pictures:
![image](https://user-images.githubusercontent.com/209056/144343775-7eb76aef-1858-42c7-b4dc-768c21bd3764.png)
![image](https://user-images.githubusercontent.com/209056/144343794-d4722953-97a9-432a-8a8f-aa758c7e0c1f.png)

As you can see, it works with SCSS, yet PostCSS seems to not detect keywords with slashes properly.

(PostCSS itself works, my Astro site builds correctly. This bug is just about how VSCode displays it.)

**Comment by jonathantneal** [comment]
This is working in the current extension. Could you check again?

```astro
<style lang="postcss">
.test {
	span {
		cursor: pointer;
		font-size: 10pt;
		font-weight: 400;
		letter-spacing: 0.04em;
		position: relative;
		text-transform: uppercase;
	}
}
</style>
```

**Comment by ptrxyz** [comment]
Yep, looks good now!
