### ISSUE TITLE
🐛 BUG: Commenting with crt+/ in the frontmatter uses an html-style comment

### ISSUE THREAD

**Issue by edazpotato** [withastro/astro-language-tools#123]
### Describe the Bug

Using <kbd>CTRL</kbd>+<kbd>/</kbd> to comment out a line or several lines creates an HTML-style comment (`<!-- -->`) instead of a js comment (`// `)

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. Open a .astro file in VS Code
3. Select some code in the frontmatter
4. Use <kbd>CTRL</kbd>+<kbd>/</kbd> to comment it out
5. Error! Describe what went wrong (and what was expected instead)...

**Comment by RafidMuhymin** [comment]
Yeah, confirmed!

**Comment by natemoo-re** [comment]
Yep, I think this was a regression due to some recent changes to the language definition. We'll take a look!

**Comment by jonathantneal** [comment]
I’m glad to know it’s a regression! I thought maybe it was always broken. This means the bug is my fault, which is good, because it means I can probably figure out why it broke and how to fix it.
